version: "3.7"

networks:
  test:
    name: fabric_test

services:
  couchdb10:
    container_name: couchdb10
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7994:5984
    networks:
      - test

  couchdb11:
    container_name: couchdb11
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8004:5984
    networks:
      - test

  peer0.retailor:
    container_name: peer0.retailor
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Org6MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test

      - CORE_PEER_ID=peer0.retailor
      - CORE_PEER_ADDRESS=peer0.retailor:9061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9061
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailor:9062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9062
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailor:9061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailor:9071

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb10
    ports:
      - 9061:9061
    volumes:
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailor/peers/peer0.retailor/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailor/peers/peer0.retailor/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

  peer1.retailor:
    container_name: peer1.retailor
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Org6MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test

      - CORE_PEER_ID=peer1.retailor
      - CORE_PEER_ADDRESS=peer1.retailor:9071
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9071
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailor:9072
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9072
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailor:9071
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailor:9061

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb11
    ports:
      - 9071:9071
    volumes:
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailor/peers/peer1.retailor/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailor/peers/peer1.retailor/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
