version: "3.7"

networks:
  test:
    name: fabric_test

services:
  couchdb8:
    container_name: couchdb8
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6034:5984
    networks:
      - test

  couchdb9:
    container_name: couchdb9
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6044:5984
    networks:
      - test

  peer0.retailer:
    container_name: peer0.retailer
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org5MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test

      - CORE_PEER_ID=peer0.retailer
      - CORE_PEER_ADDRESS=peer0.retailer:8001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8001
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer:8002
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8002
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailer:8011
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer:8001

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb8:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb8
    ports:
      - 8001:8001
    volumes:
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailer/peers/peer0.retailer/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailer/peers/peer0.retailer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

  peer1.retailer:
    container_name: peer1.retailer
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org5MSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test

      - CORE_PEER_ID=peer1.retailer
      - CORE_PEER_ADDRESS=peer1.retailer:8011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8011
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailer:8012
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8012
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailer:8011
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer:8001

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb9:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb9
    ports:
      - 8011:8011
    volumes:
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailer/peers/peer1.retailer/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../artifacts/channel/crypto-config/peerOrganizations/retailer/peers/peer1.retailer/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
